# Generated by Django 5.1.6 on 2025-03-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_post_categorey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categorey',
            new_name='category',
        ),
    ]
